    0:d=0  hl=3 l= 203 cons: SEQUENCE          
    3:d=1  hl=2 l=   1 prim:  INTEGER           :00
    6:d=1  hl=2 l=   1 prim:  INTEGER           :01
    9:d=1  hl=2 l=   1 prim:  INTEGER           :0F
   12:d=1  hl=2 l=   1 prim:  INTEGER           :10
   15:d=1  hl=2 l=   1 prim:  INTEGER           :7F
   18:d=1  hl=2 l=   2 prim:  INTEGER           :80
   22:d=1  hl=2 l=   2 prim:  INTEGER           :FF
   26:d=1  hl=2 l=   2 prim:  INTEGER           :0100
   30:d=1  hl=2 l=   2 prim:  INTEGER           :7FFF
   34:d=1  hl=2 l=   3 prim:  INTEGER           :8000
   39:d=1  hl=2 l=   3 prim:  INTEGER           :FFFF
   44:d=1  hl=2 l=   3 prim:  INTEGER           :010000
   49:d=1  hl=2 l=   8 prim:  INTEGER           :7FFFFFFFFFFFFFFF
   59:d=1  hl=2 l=   1 prim:  INTEGER           :-01
   62:d=1  hl=2 l=   1 prim:  INTEGER           :-10
   65:d=1  hl=2 l=   1 prim:  INTEGER           :-11
   68:d=1  hl=2 l=   1 prim:  INTEGER           :-80
   71:d=1  hl=2 l=   2 prim:  INTEGER           :-81
   75:d=1  hl=2 l=   2 prim:  INTEGER           :-0100
   79:d=1  hl=2 l=   2 prim:  INTEGER           :-0101
   83:d=1  hl=2 l=   2 prim:  INTEGER           :-8000
   87:d=1  hl=2 l=   3 prim:  INTEGER           :-8001
   92:d=1  hl=2 l=   3 prim:  INTEGER           :-010000
   97:d=1  hl=2 l=   3 prim:  INTEGER           :-010001
  102:d=1  hl=2 l=   8 prim:  INTEGER           :-8000000000000000
  112:d=1  hl=2 l=   1 prim:  INTEGER           :00
  115:d=1  hl=2 l=   1 prim:  INTEGER           :01
  118:d=1  hl=2 l=   1 prim:  INTEGER           :7F
  121:d=1  hl=2 l=   2 prim:  INTEGER           :80
  125:d=1  hl=2 l=   2 prim:  INTEGER           :FF
  129:d=1  hl=2 l=   2 prim:  INTEGER           :0100
  133:d=1  hl=2 l=   8 prim:  INTEGER           :7FFFFFFFFFFFFFFF
  143:d=1  hl=2 l=   9 prim:  INTEGER           :8000000000000000
  154:d=1  hl=2 l=   9 prim:  INTEGER           :FFFFFFFFFFFFFFFF
  165:d=1  hl=2 l=   1 prim:  INTEGER           :-01
  168:d=1  hl=2 l=   2 prim:  INTEGER           :-80
  172:d=1  hl=2 l=   2 prim:  INTEGER           :-81
  176:d=1  hl=2 l=   2 prim:  INTEGER           :-0100
  180:d=1  hl=2 l=   2 prim:  INTEGER           :-0101
  184:d=1  hl=2 l=   9 prim:  INTEGER           :-8000000000000000
  195:d=1  hl=2 l=   9 prim:  INTEGER           :-8000000000000001
